dotalh/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dotalh.views.home', name='home'),
    # url(r'^dotalh/', include('dotalh.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
	url(r'^game_data/', include('game_data.urls', namespace = "game_data")),
	url(r'^admin/', include(admin.site.urls)),
)

game_data/urls.py
from django.conf.urls import patterns, url
from django.views.generic.base import TemplateView

from .views import IndexView, HeroDetail, PlayerDetail, GameCreate, UserLogin, UserCreation, UserLogout

urlpatterns = patterns('',
                       url(r'^$', IndexView.as_view(), name='index'),
                       url(r'^submit_game/$', GameCreate.as_view(), name='submit_game'),
                       url(r'^successful_submit/$', TemplateView.as_view(template_name = 'game_data/successful_submit.html'), name='successful_submit'),
                       url(r'^hero/(?P<hero_name_underscored>[\w-]+)/$', HeroDetail.as_view(), name='hero_detail'),
                       url(r'^player/(?P<pk>[\w-]+)/$', PlayerDetail.as_view(), name='player_detail'),
                       url(r'^login/$', UserLogin.as_view(), name='login'),
                       url(r'^sign_up/$', UserCreation.as_view(), name='sign_up'),
                       url(r'^logout/$', UserLogout.as_view(), name='logout'))

game_data/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.core.urlresolvers import reverse
from django.db.models import F, Q, Max, Avg


class PlayerManager(models.Manager):
	def create_player(self, player_acct):
		if not player_acct:
			msg = "Player must have a name"
			raise ValueError(msg)

		player = self.create(player_acct=player_acct)
		return player

	def ranked(self, **kwargs):
		return self.filter(overall_rank__isnull=False, **kwargs)

	def worse_rank(self, rank):
		results = self.filter(overall_rank__isnull=False)
		return results.filter(Q(overall_rank__gt=rank))

	def worse_avg(self, avg_last_hits, avg_gpm):
		results = self.filter(overall_rank__isnull=False)
		return results.filter(Q(avg_last_hits=avg_last_hits, avg_gpm__lt=avg_gpm) | Q(avg_last_hits__lt=avg_last_hits))


class Player(models.Model):
	player_acct = models.ForeignKey(settings.AUTH_USER_MODEL)
	overall_rank = models.PositiveIntegerField(blank=True, null=True)
	avg_last_hits = models.DecimalField(max_digits=6, decimal_places=2, default=0, blank=True)
	avg_gpm = models.DecimalField(max_digits=6, decimal_places=2, default=0, blank=True)
	
	objects = PlayerManager()

	def __unicode__(self):
		return self.player_acct.get_short_name()


class Hero(models.Model):
	hero_name_underscored = models.CharField(max_length=60)
	hero_name = models.CharField(max_length=50)

	def __unicode__(self):
		return self.hero_name_underscored


class GameManager(models.Manager):

	def ranked(self, **kwargs):
		return self.filter(rank_number__isnull=False, **kwargs)

	def worse_rank(self, hero, rank):
		return self.filter(hero=hero, rank_number__isnull=False).filter(rank_number__gt=rank)

	def worse_games(self, hero, last_hits, gpm):
		ret_filter = self.filter(Q(last_hits=last_hits, gpm__lt=gpm) | Q(last_hits__lt=last_hits))
		ret_filter = ret_filter.filter(hero=hero, rank_number__isnull=False)
		return ret_filter


class Game(models.Model):
	player = models.ForeignKey(Player, null=True)
	hero = models.ForeignKey(Hero)
	last_hits = models.PositiveIntegerField()
	gpm = models.PositiveIntegerField()
	pub_date = models.DateTimeField(auto_now_add=True)
	rank_number = models.PositiveIntegerField(null=True)

	objects = GameManager()

	def __unicode__(self):
		return u'%s %s' % (self.hero.hero_name, self.player.player_acct)

	def get_absolute_url(self):
		return reverse('game_data:successful_submit')


class DotaUserManager(BaseUserManager):
	def create_user(self, email, gamer_tag, password=None):
		if not email:
			msg = "User must have an email address"
			raise ValueError(msg)

		if not gamer_tag:
			msg = "User must have a Gamer Tag"
			raise ValueError(msg)

		user = self.model(email=DotaUserManager.normalize_email(email), gamer_tag=gamer_tag)
		user.set_password(password)
		user.save(using=self._db)

		player = Player.objects.create_player(user)
		player.save()
		return user

	def create_superuser(self, email, gamer_tag, password):
		user = self.create_user(email, gamer_tag=gamer_tag, password=password)
		user.is_staff = True
		user.is_admin = True
		user.is_superuser = True
		user.save(using=self._db)
		return user


class DotaUser(AbstractBaseUser, PermissionsMixin):
	email = models.EmailField(verbose_name="email address", max_length=255, unique=True, db_index=True)
	gamer_tag = models.CharField(max_length=255, unique=True)

	USERNAME_FIELD = "email"
	REQUIRED_FIELDS = ["gamer_tag", ]

	is_active = models.BooleanField(default=True)
	is_admin = models.BooleanField(default=False)
	is_staff = models.BooleanField(default=False)

	objects = DotaUserManager()

	def get_short_name(self):
		return self.gamer_tag

	def __unicode__(self):
		return self.email

game_data/forms.py
from django import forms
from django.forms import ModelForm, ValidationError

from .models import Player, Hero, Game, DotaUser


class PlayerForm(ModelForm):
	class Meta:
		model = Player


class HeroForm(ModelForm):
	class Meta:
		model = Hero


class GameForm(ModelForm):
	class Meta:
		model = Game
		fields = ['hero', 'last_hits', 'gpm']


class DotaUserCreationForm(ModelForm):
	password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
	password2 = forms.CharField(label="Password confirmation", widget=forms.PasswordInput)

	class Meta:
		model = DotaUser
		fields = ("email", "gamer_tag")

	def clean_password2(self):
		password1 = self.cleaned_data.get("password1")
		password2 = self.cleaned_data.get("password2")

		if password1 and password2 and password1 != password2:
			msg = "Passwords don't match"
			raise ValidationError(msg)
		return password2

	def save(self, commit=True):
		user = super(DotaUserCreationForm, self).save(commit=False)
		user.set_password(self.cleaned_data["password1"])
		if commit:
			user.save()
			player = Player.objects.create_player(user)
			player.save()
		return user

game_data/views.py
from django.contrib.auth import login, REDIRECT_FIELD_NAME
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import logout
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, FormView

from braces.views import LoginRequiredMixin

from .forms import PlayerForm, GameForm, DotaUserCreationForm
from .models import Player, Hero, Game, DotaUser
from .rank_logic import add_update_hero_ranking, add_update_player_rank


class IndexView(ListView):
	template_name = 'game_data/index.html'
	context_object_name = 'latest_game_list'
	
	def get_queryset(self):
		return Game.objects.select_related('hero__hero_name_underscored', 'player__pk', 'player__player_acct__gamer_tag').order_by('-pub_date')[:5]
	
	def get_context_data(self, **kwargs):
		context = super(IndexView, self).get_context_data(**kwargs)
		context['hero_list'] = Hero.objects.all()
		context['player_list'] = Player.objects.select_related('player_acct__gamer_tag').all()
		return context
		
	
class HeroDetail(DetailView):
	model = Hero
	template_name = 'game_data/hero_detail.html'
	slug_field = 'hero_name_underscored'
	slug_url_kwarg = 'hero_name_underscored'
	
	def get_context_data(self, **kwargs):
		context = super(HeroDetail, self).get_context_data(**kwargs)
		hero = get_object_or_404(Hero, hero_name_underscored=self.kwargs['hero_name_underscored'])
		context['hero_game_list'] = Game.objects.ranked(hero=hero).select_related('player__pk', 'player__player_acct__gamer_tag').order_by('-last_hits', '-gpm', '-pub_date')
		return context
		
	
class PlayerDetail(DetailView):
	model = Player
	template_name = 'game_data/player_detail.html'
	
	def get_context_data(self, **kwargs):
		context = super(PlayerDetail, self).get_context_data(**kwargs)
		player = get_object_or_404(Player, pk=self.kwargs['pk'])
		context['player_game_list'] = Game.objects.filter(player=player).select_related('hero__hero_name_underscored').order_by('-last_hits', '-gpm', '-pub_date')
		return context
		

class GameCreate(LoginRequiredMixin, CreateView):
	model = Game
	form_class = GameForm
	template_name = 'game_data/submit_game.html'
	submitted_game = None

	def form_valid(self, form):
		user_player = Player.objects.filter(player_acct=self.request.user)
		form.instance.player = user_player[0]
		self.submitted_game = form.instance
		return super(GameCreate, self).form_valid(form)
		
	def get_success_url(self):
		if self.submitted_game:
			add_update_hero_ranking(self.submitted_game)
			add_update_player_rank(self.submitted_game.player)
		return super(GameCreate, self).get_success_url()


class UserLogin(FormView):
	form_class = AuthenticationForm
	redirect_field_name = REDIRECT_FIELD_NAME
	template_name = 'game_data/login.html'
	
	player_acct = ''
	
	def dispatch(self, *args, **kwargs):
		return super(UserLogin, self).dispatch(*args, **kwargs)
	
	def form_valid(self, form):
		login(self.request, form.get_user())
		self.player_acct = Player.objects.filter(player_acct=form.get_user())
		return super(UserLogin, self).form_valid(form)

	def get_success_url(self):
		if self.player_acct[0] is not None:
			success_url = reverse('game_data:player_detail', kwargs={'pk': self.player_acct[0].pk})
		else:
			success_url = reverse('game_data:index')
		return success_url


class UserCreation(FormView):
	model = DotaUser
	form_class = DotaUserCreationForm
	redirect_field_name = REDIRECT_FIELD_NAME
	template_name = 'game_data/sign_up.html'

	def dispatch(self, *args, **kwargs):
		return super(UserCreation, self).dispatch(*args, **kwargs)
	
	def form_valid(self, form):
		form.save()
		player_form = PlayerForm()
		player_form.player_acct = form
		return super(UserCreation, self).form_valid(form)

	def get_success_url(self):
		success_url = reverse('game_data:login')
		return success_url


class UserLogout(TemplateView):
	template_name = 'game_data/logout.html'

	def get(self, request, *args, **kwargs):
		get = super(UserLogout, self).get(request, *args, **kwargs)
		logout(request, next_page='game_data/index.html', template_name='game_data/logout.html')
		return get

game_data/templates/game_data/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">

	{% block css_includes %}
        {% load staticfiles %}
        <!-- Bootstrap -->
        <link href="{% static 'game_data/css/bootstrap.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'game_data/css/sticky-footer.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'game_data/css/scrollbar.css' %}" rel="stylesheet" type="text/css">
    {% endblock %}
</head>

<body style>
  <div id="wrap">
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">Last Hit</a>
        </div>

        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'game_data:index' %}">Home</a></li>
            <li><a href="{% url 'game_data:submit_game' %}">Submit Game</a></li>
            {% if user.is_authenticated %}
              <li><a href="{% url 'game_data:logout' %}">Logout</a></li>
            {% else %}
              <li><a href="{% url 'game_data:login' %}">Login</a></li>
            {%  endif %}
            <li><a href="{% url 'game_data:sign_up' %}">Sign Up</a></li>
          </ul>
        </div>
      </div>
    </div>

	<div class="container" id="content">
		<h1>{% block title %}Lorem Ipsum{% endblock %}</h1>
        {% block content %}
		{% endblock %}
	</div>
  </div>

  <div id="footer">
    <div class="container">
      <p class="text-muted credit">John Maxwell &copy;2013</p>
    </div>
  </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
</body>

</html>

game_data/templates/game_data/hero_detail.html
{% extends "game_data/base.html" %}

{% block title %}{{ hero.hero_name }}{% endblock %}


{% block content %}

<h3>Most Recent Games</h3>

{% if hero_game_list %}
	<table class="table">
	<thead>
		<th>Rank</th>
        <th>Player</th>
		<th>Last Hits</th>
		<th>GPM</th>
		<th>Published</th>
	</thead>
    {% for game in hero_game_list %}
		<tbody>
			{% if game.rank_number == None %}
				<td></td>
			{% else %}
				<td>{{ game.rank_number }}</td>
			{% endif %}
			<td><a href="{% url 'game_data:player_detail' game.player.pk %}">{{ game.player.player_acct.gamer_tag }}</a></td>
			<td>{{ game.last_hits }}</td>
			<td>{{ game.gpm }}</td>
			<td>{{ game.pub_date|timesince }}</td>
		</tbody>
    {% endfor %}
	</table>
    
{% else %}
    <p>No games available.</p>
{% endif %}

{% endblock content%}

game_data/templates/game_data/index.html
{% extends "game_data/base.html" %}
{% load staticfiles %}
{% block title %}Team Loller Learns To Last Hit!{% endblock %}


{% block content %}

{% if latest_game_list %}
    <table class="table">
	<thead>
		<th>Rank</th>
		<th>Hero</th>
        <th>Player</th>
		<th>Last Hits</th>
		<th>GPM</th>
		<th>Published</th>
	</thead>
    {% for game in latest_game_list %}
		<tbody>
			{% if game.rank_number == None %}
				<td></td>
			{% else %}
				<td>{{ game.rank_number }}</td>
			{% endif %}
			<td><a href="{% url 'game_data:hero_detail' game.hero.hero_name_underscored %}">
				<img id="base_{{game.hero.hero_name_underscored}}" 
					src="{% static 'game_data/image/'|add:game.hero.hero_name_underscored|add:'_sb.png' %}">
				</a>
			</td>
			<td><a href="{% url 'game_data:player_detail' game.player.pk %}">{{ game.player.player_acct.gamer_tag }}</a></td>
			<td>{{ game.last_hits }}</td>
			<td>{{ game.gpm }}</td>
			<td>{{ game.pub_date|timesince }}</td>
		</tbody>
    {% endfor %}
	</table>
	
{% else %}
    <p>No recent games.</p>
{% endif %}



<h3>Heroes</h3>
{% if hero_list %}
    <div class="scrollbox">
    {% for hero in hero_list %}
		<a href="{% url 'game_data:hero_detail' hero.hero_name_underscored %}">
		<img id="base_{{hero.hero_name_underscored}}" 
					src="{% static 'game_data/image/'|add:hero.hero_name_underscored|add:'_sb.png' %}">
		</a>
    {% endfor %}
    </div>
{% else %}
    <p>No heroes are available.</p>
{% endif %}


<h3>Players</h3>
{% if player_list %}
    {% for player in player_list %}
		<a href="{% url 'game_data:player_detail' player.pk %}">{{ player.player_acct.gamer_tag }}</a><br/>
    {% endfor %}
{% else %}
    <p>No players are available.</p>
{% endif %}

{% endblock content%}

game_data/templates/game_data/login.html
{% extends "game_data/base.html" %}

{% block css_includes %}
    {{ block.super }}
    {% load staticfiles %}
    <link href="{% static 'game_data/css/login.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block title %}{% endblock %}


{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form class="form-signin" action="{% url 'game_data:login' %}" method="post">
	{% csrf_token %}
	<h2 class="form-signin-heading">Please sign in</h2>
    <input id="{{ form.username.id_for_label }}" name="{{ form.username.html_name }}" type="text" class="form-control" placeholder="{{ form.username.label }}" required="" autofocus="">
    <input id="{{ form.password.id_for_label }}" name="{{ form.password.html_name }}" type="password" class="form-control" placeholder="{{ form.password.label }}" required="">
    <!--<table>
	<tr>
		<td>{{ form.username.label_tag }}</td>
		<td>{{ form.username }}</td>
	</tr>
	<tr>
		<td>{{ form.password.label_tag }}</td>
		<td>{{ form.password }}</td>
	</tr>
	</table>-->
	<button class="btn btn-lg btn-default btn-block" type="submit">Sign in</button>
    <!--<input type="submit" value="Submit" />-->
	<input type="hidden" name="next" value=" {{next}} " />
</form>

{% endblock content%}

game_data/templates/game_data/logout.html
{% extends "game_data/base.html" %}

{% block title %}Logout{% endblock %}


{% block content %}

<h2>Successfully logged out</h2>

{% endblock content%}

game_data/templates/game_data/player_detail.html
{% extends "game_data/base.html" %}
{% load staticfiles %}
{% block title %}{{ player }}&nbsp 
	{% if player.overall_rank != None %}
		{{player.overall_rank}}
	{% endif %}
{% endblock %}


{% block content %}

{% if player_game_list %}
	<table class="table">
	<thead>
		<th>Rank</th>
		<th>Hero</th>
		<th>Last Hits</th>
		<th>GPM</th>
		<th>Published</th>
	</thead>
    {% for game in player_game_list %}
		<tbody>
			{% if game.rank_number == None %}
				<td></td>
			{% else %}
				<td>{{ game.rank_number }}</td>
			{% endif %}
			<td><a href="{% url 'game_data:hero_detail' game.hero.hero_name_underscored %}">
				<img id="base_{{game.hero.hero_name_underscored}}"
					src="{% static 'game_data/image/'|add:game.hero.hero_name_underscored|add:'_sb.png' %}">
				</a>
			</td>
			<td>{{ game.last_hits }}</td>
			<td>{{ game.gpm }}</td>
			<td>{{ game.pub_date|timesince }}</td>
		</tbody>
    {% endfor %}
	</table>
    
{% else %}
    <p>No games available.</p>
{% endif %}

{% endblock content%}

game_data/templates/game_data/sign_up.html
{% extends "game_data/base.html" %}

{% block title %}Sign Up{% endblock %}


{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'game_data:sign_up' %}" method="post">
	{% csrf_token %}
    <table>
	<tr>
		<td>{{ form.email.label_tag }}</td>
		<td>{{ form.email }}</td>
	</tr>
    <tr>
        <td>{{ form.gamer_tag.label_tag }}</td>
        <td>{{ form.gamer_tag }}</td>
    </tr>
	<tr>
		<td>{{ form.password1.label_tag }}</td>
		<td>{{ form.password1 }}</td>
	</tr>
	<tr>
		<td>{{ form.password2.label_tag }}</td>
		<td>{{ form.password2 }}</td>
	</tr>
	</table>
	<input type="submit" value="Submit" />
	<input type="hidden" name="next" value=" {{next}} " />
</form>

{% endblock content%}

game_data/templates/game_data/submit_game.html
{% extends "game_data/base.html" %}

{% block title %}Submit Game{% endblock %}


{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'game_data:submit_game' %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit" />
</form>

{% endblock content%}

game_data/templates/game_data/successful_submit.html
{% extends "game_data/base.html" %}

{% block title %}Game Submitted{% endblock %}


{% block content %}
<p> Game data successfully submitted </p>

{% endblock content%}